name: Free Windows RDP with remote.it

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    env:
      REMOTEIT_API_KEY: ${{ secrets.REMOTEIT_API_KEY }}  # simpan API key di Secrets

    steps:
    - name: Download remote.it CLI
      run: |
        Invoke-WebRequest -Uri https://install.remote.it/windows/latest -OutFile remoteit.msi
        Start-Process msiexec.exe -ArgumentList '/i', 'remoteit.msi', '/quiet', '/norestart' -Wait

    - name: Enable RDP and Firewall
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Log in to remote.it CLI
      run: |
        & "C:\Program Files\remote.it\remoteit.exe" login --apikey $Env:REMOTEIT_API_KEY

    - name: Register RDP Service with remote.it
      id: register
      run: |
        # Daftarkan device dulu (gunakan hostname runner)
        $deviceName = hostname
        $device = & "C:\Program Files\remote.it\remoteit.exe" adddevice $deviceName | ConvertFrom-Json
        $deviceId = $device.id

        # Daftarkan service RDP (TCP port 3389)
        $service = & "C:\Program Files\remote.it\remoteit.exe" addservice $deviceId --name "Windows RDP" --protocol tcp --port 3389 | ConvertFrom-Json

        # Simpan Service ID ke output
        Write-Host "::set-output name=serviceId::$($service.id)"

    - name: Get Access Info
      run: |
        # List access links
        $serviceId = '${{ steps.register.outputs.serviceId }}'
        $links = & "C:\Program Files\remote.it\remoteit.exe" connect $serviceId --json | ConvertFrom-Json

        Write-Output "======================================="
        Write-Output "RDP is ready via remote.it!"
        Write-Output "Access Endpoint(s):"
        foreach ($link in $links.accessLinks) {
          Write-Output "  Host: $($link.host)"
          Write-Output "  Port: $($link.port)"
          Write-Output "  Protocol: $($link.protocol)"
        }
        Write-Output "Username: administrator"
        Write-Output "Password: JohnTech1234"
        Write-Output "======================================="

    - name: Keep session alive
      run: |
        for ($i=0; $i -lt 360; $i++) {
          Write-Host "⏳ RDP active... Hour $i"
          Start-Sleep -Seconds 3600
        }
