name: Remote.it RDP Setup

on: workflow_dispatch

jobs:
  setup-rdp:
    runs-on: windows-latest
    timeout-minutes: 360

    env:
      REMOTEIT_API_KEY: ${{ secrets.REMOTEIT_API_KEY }}   # Masukkan API Key remote.it di Secrets GitHub
      REMOTEIT_DEVICE_NAME: "github-runner-rdp"

    steps:
    - name: Download remote.it MSI dari Google Drive
      run: |
        Invoke-WebRequest -Uri "https://drive.google.com/uc?export=download&id=1uQZqT9xUSV-rsVjtQyo7jbOBYbWQoLTv" -OutFile remoteit.msi

    - name: Install remote.it secara silent
      run: |
        Start-Process msiexec.exe -ArgumentList '/i', 'remoteit.msi', '/quiet', '/norestart' -Wait

    - name: Login ke remote.it CLI
      run: |
        remoteit.exe login --apikey $Env:REMOTEIT_API_KEY

    - name: Register device (jika belum ada)
      run: |
        $deviceExists = remoteit.exe listdevices | Select-String $Env:REMOTEIT_DEVICE_NAME
        if (-not $deviceExists) {
          remoteit.exe adddevice --name $Env:REMOTEIT_DEVICE_NAME
        }

    - name: Enable RDP dan Firewall Windows
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Add RDP service to remote.it device
      run: |
        # Dapatkan device id
        $device = remoteit.exe listdevices | Select-String $Env:REMOTEIT_DEVICE_NAME
        $deviceId = ($device -split '\s+')[0]

        # Tambah service RDP TCP 3389
        remoteit.exe addservice --deviceid $deviceId --name "RDP" --protocol tcp --port 3389

    - name: List services untuk cek endpoint
      run: |
        remoteit.exe listservices

    - name: Keep session alive
      run: |
        for ($i=0; $i -lt 360; $i++) {
          Write-Host "⏳ RDP is active... Hour $i"
          Start-Sleep -Seconds 3600
        }
