name: Free Windows RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    steps:
    - name: Download tools
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Expand-Archive ngrok.zip -DestinationPath ngrok

    - name: Connect Ngrok Account
      run: |
        .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN

    - name: Enable RDP and firewall rules
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Creating Tunnel and Showing IP
      run: .\ngrok\ngrok.exe tcp 3389 --log=stdout

    - name: Show RDP Credentials
      run: |
        $hostname = hostname
        Write-Output "========================================"
        Write-Output "RDP is now ready!"
        Write-Output "Username: administrator"
        Write-Output "Password: JohnTech1234"
        Write-Output "Use the Ngrok forwarding address from the tunnel"
        Write-Output "========================================"

    - name: Keep session alive
      run: |
        for ($i = 0; $i -lt 999; $i++) {
          Write-Host "RDP Running... Hour $i"
          Start-Sleep -Seconds 3600
        }
