name: Setup Remote.it RDP

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360

    env:
      REMOTEIT_API_KEY: ${{ secrets.REMOTEIT_API_KEY }}

    steps:
    - name: Download remote.it MSI installer
      run: |
        Invoke-WebRequest -Uri "https://install.remote.it/windows/latest" -OutFile remoteit.msi
      shell: powershell

    - name: Install remote.it silently
      run: msiexec.exe /i remoteit.msi /quiet /norestart

    - name: Login ke remote.it CLI
      run: |
        $remoteitPath = "C:\Program Files (x86)\remote.it\remoteit.exe"
        & $remoteitPath login --apikey $Env:REMOTEIT_API_KEY
      shell: powershell

    - name: Enable RDP + Firewall
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
      shell: powershell

    - name: Daftarkan service RDP di remote.it
      run: |
        $remoteitPath = "C:\Program Files (x86)\remote.it\remoteit.exe"
        & $remoteitPath add --name "Windows RDP" --protocol tcp --port 3389 --localport 3389
      shell: powershell

    - name: List devices dan services remote.it (cek service aktif)
      run: |
        $remoteitPath = "C:\Program Files (x86)\remote.it\remoteit.exe"
        & $remoteitPath list
      shell: powershell

    - name: Keep session alive
      run: |
        for ($i=0; $i -lt 360; $i++) {
          Write-Host "Remote.it RDP is active... Hour $i"
          Start-Sleep -Seconds 3600
        }
      shell: powershell
