    - name: Login ke remote.it CLI
      shell: powershell
      run: |
        $remoteitPath = "C:\Program Files (x86)\remote.it\remoteit.exe"
        & "$remoteitPath" login --apikey $Env:REMOTEIT_API_KEY

    - name: Daftarkan service RDP di remote.it
      shell: powershell
      run: |
        $remoteitPath = "C:\Program Files (x86)\remote.it\remoteit.exe"
        & "$remoteitPath" add --name "Windows RDP" --protocol tcp --port 3389 --localport 3389

    - name: List devices dan services remote.it
      shell: powershell
      run: |
        $remoteitPath = "C:\Program Files (x86)\remote.it\remoteit.exe"
        & "$remoteitPath" list

    - name: Keep session alive
      shell: powershell
      run: |
        for ($i=0; $i -lt 360; $i++) {
          Write-Host "Remote.it RDP is active... Hour $i"
          Start-Sleep -Seconds 3600
        }
